global:
  resolve_timeout: 5m
route:
  receiver: discord
receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discord.com/api/webhooks/1308088970806169704/-GF3pEIHfzVhwFsKbme_ACsF6snGG0b6e2M5rv95VSYmTAItO2FrZ4cgPFe3Z9kOn3qr
