global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: https://webhook.site/ee8285f9-afe9-400f-a0da-a2c9fc5c8f26
          send_resolved: false