version: '3'
volumes:
  database_data:
services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx config file
    depends_on:
      - gold-price
      - rate-exchange

  # gold-price folder
  gold-price:
    build: ./gold-price
    image: gold-price/gold-price-vn:1.2.1
    container_name: gold-price
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=statistic_log
      - DB_USER=postgres
      - DB_PASSWORD=ppaasssswwoorrdd
    expose:
      - "8000"
    depends_on:
      - database

  # rate-exchange folder
  rate-exchange:
    build: ./rate-exchange
    image: rate-exchange/rate-exchange-vnd:1.1.0
    container_name: rate-exchange
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=statistic_log
      - DB_USER=statistic_user
      - DB_PASSWORD=statistic_password
    expose:
      - "8000"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres_database
    environment:
      - POSTGRES_PASSWORD=ppaasssswwoorrdd
    expose:
      - "5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql