version: '3'
volumes:
  database_data:
services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    # volumes:
    #   - /home/egnaro/health-endpoint-monitoring-lab/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx config file
    depends_on:
      - gold-price
      - rate-exchange

  gold-price:
    image: gold-price:latest      # ???
    container_name: gold-price
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=statistic_log
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    expose:
      - "8081:8080"
    depends_on:
      - database

  rate-exchange:
    image: rate-exchange:latest                      # ???
    container_name: rate-exchange
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=statistic_log
      - DB_USER=statistic_user
      - DB_PASSWORD=statistic_password
    expose:
      - "8082:8080"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    # volumes:
    #   - database_data:/var/lib/postgresql/data
    #   - /home/egnaro/health-endpoint-monitoring-lab/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql