global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

rule_files:
  - /etc/prometheus/rules.yml

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#        - alertmanager:9093

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets:
        - host.docker.internal:9323
  - job_name: 'nginx-prometheus-exporter'      
    static_configs:
      - targets: 
        - nginx-prometheus-exporter:9113
  - job_name: 'fluentd'      
    static_configs:
      - targets: 
        - fluentd:24231
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - prometheus:9090
  - job_name: 'cadvisor' 
    scrape_interval: 5s
    static_configs:
      - targets: 
        - cadvisor:8080
  - job_name: 'node-exporter'      
    static_configs:
      - targets: 
        - node-exporter:9100
        