{
 "title": "Alert",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Alert",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ALERTS)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container Killed",
   "type": "stat",
   "description": "A container has disappeared",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"ContainerKilled\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container High Cpu Utilization",
   "type": "stat",
   "description": "Container CPU utilization is above 80%",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"ContainerHighCpuUtilization\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container High Memory Usage",
   "type": "stat",
   "description": "Container Memory usage is above 80%",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"ContainerHighMemoryUsage\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Volume Usage",
   "type": "stat",
   "description": "Container Volume usage is above 80%",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"ContainerVolumeUsage\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container High Throttle Rate",
   "type": "stat",
   "description": "Container is being throttled",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"ContainerHighThrottleRate\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Alert",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "ALERTS", "legendFormat": "__auto" }
   ]
  }
 ]
}