{
 "title": "Request count",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_request_status_code_total{upstream_status=~\"2..\"})",
     "legendFormat": "Code 200 Requests"
    },
    {
     "expr": "sum(nginx_request_status_code_total{upstream_status=~\"4..\"})",
     "legendFormat": "Code 400 Requests"
    },
    {
     "expr": "sum(nginx_request_status_code_total{upstream_status=~\"5..\"})",
     "legendFormat": "Code 500 Requests"
    }
   ]
  },
  { "title": "NGINX Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Connections Accepted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_accepted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections Hanled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_handled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NGINX Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections Active",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections Writing",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_writing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections Waiting",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_waiting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections Dropped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_accepted - nginx_connections_handled",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Reading",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_reading", "legendFormat": "__auto" }
   ]
  },
  { "title": "Request Counter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Show the how many requests in minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_request_status_code_total{request!~\"GET /gold-price.*|GET /rate-exchange.\"}[1m]))",
     "legendFormat": "/dashboard"
    },
    {
     "expr": "sum(rate(nginx_request_status_code_total{request=~\"GET /gold-price.*\"}[1m]))",
     "legendFormat": "/gold-price"
    },
    {
     "expr": "sum(rate(nginx_request_status_code_total{request=~\"GET /rate-exchange.*\"}[1m]))",
     "legendFormat": "/rate-exchange"
    }
   ]
  },
  {
   "title": "Percentages (by Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(nginx_request_status_code_total{request!~\"GET /gold-price.*|GET /rate-exchange.\"})",
     "legendFormat": "/dashboard"
    },
    {
     "expr": "sum(nginx_request_status_code_total{request=~\"GET /gold-price.*\"})",
     "legendFormat": "/gold-price"
    },
    {
     "expr": "sum(nginx_request_status_code_total{request=~\"GET /rate-exchange.*\"})",
     "legendFormat": "/rate-exchange"
    }
   ]
  },
  {
   "title": "Percentages (by Status)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_request_status_code_total{upstream_status=~\"2..\"})",
     "legendFormat": "Code 200"
    },
    {
     "expr": "sum(nginx_request_status_code_total{upstream_status=~\"4..\"})",
     "legendFormat": "Code 400"
    },
    {
     "expr": "sum(nginx_request_status_code_total{upstream_status=~\"5..\"})",
     "legendFormat": "Code 500"
    }
   ]
  }
 ]
}